spring:
  datasource_old:
    url: jdbc:h2:mem:sample-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://psyko460.fr:3306
    username: ebt
    password: ebt
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

application:
  transaction:
    url: http://localhost:8086
    features:
      create: /transaction/create